import { db } from "@/configs/db";
import { STUDY_MATERIAL_TABLE } from "@/configs/schema";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";

export async function GET(req) {
  try {
    // Extract user email from URL query parameter
    const url = new URL(req.url);
    const userEmail = url.searchParams.get("email");

    if (!userEmail) {
      return NextResponse.json({ error: "Missing email parameter" }, { status: 400 });
    }

    // Count courses generated by the user
    const courses = await db.select()
      .from(STUDY_MATERIAL_TABLE)
      .where(eq(STUDY_MATERIAL_TABLE.createdBy, userEmail));

    return NextResponse.json({ 
      count: courses.length 
    });
    
  } catch (error) {
    console.error('Error fetching user courses count:', error);
    return NextResponse.json({ 
      error: "Failed to fetch courses count",
      details: error.message 
    }, { status: 500 });
  }
}
